### ISSUE TITLE
Basic issue

### ISSUE THREAD

**Issue by shinyahamada** [shinyahamada/dinner#1]
- [ ] #2 Home(create & select) Page like spa
- [ ] #3 DB model (daily & list & ingredient)
- [ ] #4 notify others select Line or ...? (from events in application)
- [ ] #5 Daily notification to Line (daily patch)
